scrape_configs:
  - job_name: 'springboot-actuator'
    scrape_interval: 5s
    scrape_timeout: 10s
    static_configs:
      - targets: ['localhost:8080']
    metrics_path: /actuator/prometheus

  - job_name: 'kafka'
    scrape_interval: 5s
    scrape_timeout: 10s
    static_configs:
      - targets: ['localhost:9404']

  - job_name: 'redis'
    scrape_interval: 5s
    scrape_timeout: 10s
    static_configs:
      - targets: ['localhost:9121']

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['localhost:9093']

rule_files:
  - 'alert.rules.yml'



