scrape_configs:
  - job_name: 'springboot-actuator'
    scrape_timeout: 30s
    static_configs:
      - targets: ['localhost:8080']
    metrics_path: /actuator/prometheus

  - job_name: 'redis'
    scrape_timeout: 30s
    static_configs:
      - targets: ['localhost:9121']

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['localhost:9093']

rule_files:
  - 'alert.rules.yml'
