scrape_configs:
  - job_name: 'springboot-actuator'
    static_configs:
      - targets: ['127.0.0.1:8080']
    metrics_path: /actuator/prometheus

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['127.0.0.1:9093']

rule_files:
  - 'alert.rules.yml'


